name: CI

on: [push, workflow_dispatch]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend-notes
    steps:
      - uses: actions/checkout@v2
      - name: npm install and build frontend
        run: |
          npm install
          npm run build --if-present
      - uses: actions/upload-artifact@main
        with:
          name: build
          path: ./frontend-notes/build/
  deploy:
      needs: build-frontend
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/download-artifact@main
          with:
            name: build
        - run: ls
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy --remote-only
  
        
        
